name: ssum CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: compile shared library
      run: make install-lib
      run: export LD_LIBRARY_PATH=${HOME}/.local/lib/:${LD_LIBRARY_PATH}
    - name: compile ssum
      run: make
    - name: make test
      run: make test
