name: ssum CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: configure
      run: ./configure

    - name: compile shared library
      run: make install-lib

    - name: compile ssum
      run: make

    - name: make test
      run: export LD_LIBRARY_PATH=${HOME}/.local/lib/:${LD_LIBRARY_PATH} && make test

